# Generated by Django 3.2 on 2022-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crudemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('F', 'Frontenddev'), ('B', 'Backenddev')], default='', max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('companyname', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
